### ISSUE TITLE
Startup "Attempted to register a second handler for 'action-invoke'" (MacOS)

### ISSUE THREAD

**Issue by evinowen** [evinowen/tome#79]
Error on startup on MacOS

```
[2023-06-13 15:11:28.338] [info]  Main Process Start
[2023-06-13 15:11:28.713] [info]  Application Ready
[2023-06-13 15:11:28.717] [info]  Application Present
[2023-06-13 15:11:28.719] [info]  Building window for environment undefined
[2023-06-13 15:11:28.876] [info]  Window build complete
[2023-06-13 15:11:28.878] [info]  Registering components with built window
[2023-06-13 15:11:28.878] [info]  Reset listeners for IPC communication
[2023-06-13 15:11:28.880] [info]  Register main process components
[2023-06-13 15:11:28.880] [info]  Register component action
[2023-06-13 15:11:28.884] [info]  Register component clipboard
[2023-06-13 15:11:28.885] [info]  Register component file
[2023-06-13 15:11:28.888] [info]  Register component repository
[2023-06-13 15:11:28.890] [info]  Register component app
[2023-06-13 15:11:28.893] [info]  Register component path
[2023-06-13 15:11:28.913] [info]  Register component ssl
[2023-06-13 15:11:28.925] [info]  Register component template
[2023-06-13 15:11:28.925] [info]  Register component window
[2023-06-13 15:11:28.925] [info]  Component registration complete
[2023-06-13 15:11:28.932] [info]  Loading the window index
[2023-06-13 15:11:32.224] [info]  Process event: application activate darwin
[2023-06-13 15:11:32.233] [info]  Application Present
[2023-06-13 15:11:32.234] [info]  Building window for environment undefined
[2023-06-13 15:11:32.246] [info]  Window build complete
[2023-06-13 15:11:32.247] [info]  Registering components with built window
[2023-06-13 15:11:32.247] [info]  Reset listeners for IPC communication
[2023-06-13 15:11:32.247] [info]  Register main process components
[2023-06-13 15:11:32.248] [info]  Register component action
[2023-06-13 15:11:32.249] [error] Error: Attempted to register a second handler for 'action-invoke'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:189:337)
    at handle (/Applications/Tome.app/Contents/Resources/app.asar/dist/main/components/factory.js:16:28)
    at exports.default.environment.environment (/Applications/Tome.app/Contents/Resources/app.asar/dist/main/components/actions/index.js:29:5)
    at Object.register (/Applications/Tome.app/Contents/Resources/app.asar/dist/main/components/factory.js:33:20)
    at Function.register (/Applications/Tome.app/Contents/Resources/app.asar/dist/main/main.js:101:27)
    at Function.<anonymous> (/Applications/Tome.app/Contents/Resources/app.asar/dist/main/main.js:88:18)
    at Generator.next (<anonymous>)
    at /Applications/Tome.app/Contents/Resources/app.asar/dist/main/main.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Tome.app/Contents/Resources/app.asar/dist/main/main.js:4:12)
[2023-06-13 15:11:32.252] [info]  Application Shutdown
[2023-06-13 15:11:32.321] [error] Unhandled Exception Error: ERR_FAILED (-2) loading 'file:///Applications/Tome.app/Contents/Resources/app.asar/index.html'
    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:161:8022)
    at EventEmitter.emit (node:events:390:28)
    ```

**Comment by evinowen** [comment]
This should be resolved with #80 and release https://github.com/evinowen/tome/releases/tag/0.7.4
